//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adisyon.Modeller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int ıd { get; set; }
        public Nullable<int> MasaId { get; set; }
        public Nullable<System.DateTime> AcilmaZamani { get; set; }
        public Nullable<bool> AcikMi { get; set; }
        public Nullable<System.DateTime> KapanmaZamani { get; set; }
    }
}
