//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adisyon.Modeller
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int ıd { get; set; }
        public Nullable<int> SiparisId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<decimal> Tutar { get; set; }
    }
}
